//esto lo hice para poder solo copiar y pegar cada que se enecesite subir el api gateway

2E-unaldo-api-gateway

version: '2'
services:
  unaldo-api:
    image: bsdiaza/test
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      USERS_URL: '35.237.244.118'
      USERS_PORT: '3000'
      USERS_ENTRY: '/'
      BOARDS_URL: '35.237.244.118'
      BOARDS_PORT: '3001'
      BOARDS_ENTRY: 'boards-ms/resources/boards'
      LISTS_URL: '35.237.244.118'
      LISTS_PORT: '3002'
      LISTS_ENTRY: 'lists-ms/resources/lists'
      TASKS_URL: '35.237.244.118'
      TASKS_PORT: '3003'
      TASKS_ENTRY: 'tasks-ms/resources/tasks'
      STATISTICS_URL: '35.237.244.118'
      STATISTICS_PORT: '3004'
      STATISTICS_ENTRY: 'statistics-ms/resources/statistics'
    ports:
      - 5000:5000
