version: '2.1'
services:
  trello-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      TASKS_URL: '192.168.99.101'
      TASKS_PORT: '3000'
      TASKS_ENTRY: 'tasks-ms/resources/tasks'
    ports:
      - '5000:5000'