version: '2'
services:
  unaldo-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      USERS_PORT: '3000'
      USERS_ENTRY: '/'
      BOARDS_PORT: '3001'
      BOARDS_ENTRY: 'boards-ms/resources/boards'
      LISTS_PORT: '3002'
      LISTS_ENTRY: 'lists-ms/resources/lists'
      TASKS_PORT: '3003'
      TASKS_ENTRY: 'tasks-ms/resources/tasks'
      STATISTICS_PORT: '3004'
      STATISTICS_ENTRY: 'statistics-ms/resources/statistics'
    ports:
      - '5000:5000'
